[package]
name = "file-encrypt-decrypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aead = "0.5.2"
anyhow = "1.0.73"
chacha20poly1305 = "0.10.1"
rand_core = "0.6.4"


